name: Release and deploy
on:
  push:
    branches: [ master ]
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: v${{ env.PACKAGE_VERSION }}
          name: v${{ env.PACKAGE_VERSION }}
          body: v${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: false
          makeLatest: true
          generateReleaseNotes: true
  deploy:
    name: Publish npm package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: npm install
        run: npm install
      - name: build
        run: npx tsc --project tsconfig-prod.json
      - name: publish
        uses: JS-DevTools/npm-publish@v2.1.0
        with:
          token: ${{ secrets.NPM_SECRET }}